spring:
#  配置数据库连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
#    开启隐藏请求方法，使用RESTful风格的接口
  mvc:
    hiddenmethod:
      filter:
        enabled: true

#  开启mybatis查询日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/liuwohe/repository/*.xml
